systemLog:
  destination: file
  path: "/var/log/mongodb/mongod.log"
  quiet: true
  logAppend: true
  component:
    network:
      verbosity: 0  # Silencia logs de conexión
    command:
      verbosity: 0

setParameter:
  logLevel: 1  # Nivel global de logs (0-5, donde 1 es solo errores importantes)